[package]
name = "albertdb"
version = "0.1.0"
edition = "2021"

[lib]
name = "albertdb"
path = "src/lib.rs"

[[bin]]
name = "main1"
path = "src/bin/main.rs"

[dependencies]
actix-web = "3"
rand = "0.8.4"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.61"
